#pragma once

enum ConfiguredPin {
  PIN_LED = 2,
  PIN_PUMP_1_ENABLE = 16,
  PIN_PUMP_2_ENABLE = 17,
  PIN_PUMP_3_ENABLE = 18, 
  PIN_PUMP_4_ENABLE = 19,
  PIN_DISTANCE_TRIGGER = 32,
  PIN_DISTANCE_ECHO = 33,
  PIN_MOISTURE_SENSOR_3 = 34,
  PIN_MOISTURE_SENSOR_4 = 35,
  PIN_MOISTURE_SENSOR_1 = 36,
  PIN_MOISTURE_SENSOR_2 = 39
};