#pragma once

enum ConfiguredPin {
  PIN_LED = 2,
  PIN_PUMP_MID_ENABLE = 16,
  PIN_PUMP_BOTTOM_ENABLE = 17,
  PIN_PUMP_TOP_ENABLE = 18, 
  PIN_PUMP_4_ENABLE = 19,
  PIN_DISTANCE_TRIGGER = 32,
  PIN_DISTANCE_ECHO = 33,
  PIN_MOISTURE_SENSOR_TOP = 34,
  PIN_MOISTURE_SENSOR_4 = 35,
  PIN_MOISTURE_SENSOR_MID = 36,
  PIN_MOISTURE_SENSOR_BOTTOM = 39
};